parameters:
    mongo.db     : 'booothy_db'
    mongo.server : 'mongodb://mongodb_dev:27017'

    booothy_api_url            : 'http://booothy.dev/index_dev.php/api/'
    booothy_download_url       : 'http://booothy.dev/index_dev.php/u/{filename}'
    booothy_thumb_download_url : 'http://booothy.dev/index_dev.php/u/thumb/{filename}'
