parameters:
    google.client_id     : 'booothy_id'
    google.client_secret : 'booothy_secret'

    folder.cache          : 'booothy/folder/cache/'
    folder.logs           : 'booothy/folder/logs/'
    folder.tmp            : 'booothy/folder/tmp/'
    folder.uploads        : 'booothy/folder/uploads/'
    folder.uploads.thumbs : 'booothy/folder/uploads/thumbs/'

    mongo.db     : 'booothy_db'
    mongo.server : 'mongodb://mongodb_dev:27017'

    booothy_api_url            : '//booothy.dev/index_dev.php/api/'
    booothy_download_url       : '//booothy.dev/index_dev.php/u/{filename}'
    booothy_thumb_download_url : '//booothy.dev/index_dev.php/u/thumb/{filename}'
