parameters:
    mongo.db     : 'booothy_db'
    mongo.server : 'mongodb://mongodb_prod:27017'

    booothy_api_url            : 'http://booothy.prod/api/'
    booothy_download_url       : 'http://booothy.prod/u/{filename}'
    booothy_thumb_download_url : 'http://booothy.prod/u/thumb/{filename}'
